"""initial-commit

Revision ID: 2425d0795eca
Revises: 
Create Date: 2026-08-06 11:00:18.841408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = '2425d0795eca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Produtos',
    sa.Column('cod_prod', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('quant_estoque', sa.Integer(), nullable=False),
    sa.Column('saidas', sa.Integer(), nullable=False),
    sa.Column('saidas_commbo', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_index(op.f('ix_Produtos_cod_prod'), 'Produtos', ['cod_prod'], unique=False)
    op.create_table('Users',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('role', sa.Enum('USER', 'SUPERUSER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.create_index(op.f('ix_Users_nome'), 'Users', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_nome'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Produtos_cod_prod'), table_name='Produtos')
    op.drop_table('Produtos')
    # ### end Alembic commands ###
